export const tagData: string[] = [
  "View All",
  "Frontend",
  "Backend",
  "System Design",
  "Mathematics",
  "Networking",
  "Data Structures",
  "Algorithms",
  "Machine Learning",
  "Data Science",
  "Computer Fundamentals",
  "Web Security",
  "Devops",
];
